service: ${env:SERVICES_NAME_PREFIX}-app

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.${env:SERVICES_NAME_PREFIX}Handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
