service: ${env:SERVICES_NAME_PREFIX}-app

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${file(./${env:SERVICES_NAME_PREFIX}.yml):environment.stage}
  region: us-east-1

functions: ${file(./${env:SERVICES_NAME_PREFIX}.yml):functions}
